---
- name: Disable systemd service
  ansible.builtin.include_tasks: commands/stop.yml

- name: Uninstall metrics
  ansible.builtin.include_role:
    name: depin.core.metrics

- name: Delete content & directory
  become: true
  ansible.builtin.file:
    state: absent
    path: "{{ _delete }}"
  loop:
    - /opt/autonomi/{{ autonomi_version }}
    - /etc/systemd/system/autonomi.service
  loop_control:
    loop_var: _delete

- name: Remove all safenode-manager files
  ansible.builtin.command: 
    cmd: safenode-manager reset --force
  changed_when: false
  failed_when: false
