---
- name: Deploy
  hosts: localhost
  gather_facts: true
  become: true
  vars:
    # @todo - pull this from source
    min_available_memory_mb: 4096
    min_available_disk_gb: 120
  tasks:
    - name: Check available memory
      ansible.builtin.assert:
        that:
          - ansible_facts['memfree_mb'] | int >= min_available_memory_mb
        fail_msg: "Not enough free memory. Required: {{ min_available_memory_mb }}MB, Available: {{ ansible_facts['memfree_mb'] | int }}MB"
        success_msg: "Sufficient free memory available"

    - name: Check disk space
      when: ansible_facts['mounts'] is defined
      block:
        - name: Calculate available disk space
          ansible.builtin.set_fact:
            available_disk_gb: |
              {{
                (ansible_facts['mounts'] | selectattr('mount', 'equalto', '/') |
                map(attribute='size_available') | list | first | int / 1024 / 1024 / 1024) |
                round(2)
              }}

        - name: Check available disk space
          ansible.builtin.assert:
            that:
              - available_disk_gb | float >= min_available_disk_gb
            fail_msg: "Not enough free disk space. Required: {{ min_available_disk_gb }}GB, Available: {{ available_disk_gb }}GB"
            success_msg: "Sufficient free disk space available"

    - name: Check load average
      ansible.builtin.assert:
        that:
          - ansible_facts['loadavg']['1m'] | float <= (ansible_facts['processor_cores'] | int - 2)
        fail_msg: "System load is too high: {{ ansible_facts['loadavg']['1m'] }}"
        success_msg: "System load is acceptable"

    - name: Request a VM
      ansible.builtin.uri:
        url: "http://example.com"
        return_content: true
        status_code: 200
      register: _job

    - name: Wait for VM
      ansible.builtin.uri:
        url: "http://example.com"
        return_content: true
        status_code: 200
      register: _vm
      until: url_check.status == 200
      retries: 60  # Number of retries
      delay: 10

    # trigger deploy
    - name: Debug
      ansible.builtin.debug:
        msg: "{{ _vm }}"
