---
- name: Deploy
  hosts: localhost
  gather_facts: true
  become: true
  vars:
    # @todo - pull this from source
    min_available_memory_mb: 4096
    min_available_disk_gb: 120
  tasks:
    - name: Check available memory
      ansible.builtin.assert:
        that:
          - ansible_facts['memfree_mb'] | int >= min_available_memory_mb
        fail_msg: "Not enough free memory. Required: {{ min_available_memory_mb }}MB, Available: {{ ansible_memfree_mb | int }}MB"
        success_msg: "Sufficient free memory available"

    - name: Check disk space
      when: ansible_mounts is defined
      block:
        - name: Calculate available disk space
          ansible.builtin.set_fact:
            available_disk_gb: |
              {{
                (ansible_mounts | selectattr('mount', 'equalto', '/') |
                map(attribute='size_available') | list | first | int / 1024 / 1024 / 1024) |
                round(2)
              }}

        - name: Check available disk space
          ansible.builtin.assert:
            that:
              - available_disk_gb | float >= min_available_disk_gb
            fail_msg: "Not enough free disk space. Required: {{ min_available_disk_gb }}GB, Available: {{ available_disk_gb }}GB"
            success_msg: "Sufficient free disk space available"

    - name: Check load average
      ansible.builtin.assert:
        that:
          - ansible_loadavg['1m'] | float <= (ansible_facts['processor_cores'] | int - 2)
        fail_msg: "System load is too high: {{ ansible_loadavg['1m'] }}"
        success_msg: "System load is acceptable"

    - name: Debugging
      ansible.builtin.debug:
        msg: "{{ ansible_nodename }}"

    - name: Request a VM
      ansible.builtin.uri:
        url: "https://api.nerdnode.io/api/v2/device/claim?device={{ ansible_nodename }}"
        return_content: true
        status_code: 200
      register: _claim

    ## should save this to file for persistance.. database? 🤓
    - name: Debugging
      ansible.builtin.debug:
        msg: "{{ _claim['json'] }}"

    - name: Wait for VM
      when: _claim['json']['job_id'] is defined
      ansible.builtin.uri:
        url: "https://api.nerdnode.io/api/v2/device/claim/results?job={{ _claim['json']['job_id'] }}"
        return_content: true
        status_code: [200, 206]
      register: claim_results
      until: claim_results['json']['vm'] is defined
      failed_when:
        - claim_results['status'] not in [200, 206]
      retries: 60
      delay: 10

    # trigger deploy
    - name: Debug
      ansible.builtin.debug:
        msg: "{{ claim_results['json'] | default(_claim['json']) }}"

    # virtualization_role
    # host == device
    # guest == vm
