- name: Update Netbox
  hosts: localhost
  gather_facts: true
  vars:
    hostname: "{{ vm_hostname | default(lookup('pipe', 'hostname -s')) | split('.') | first }}"
    vm_id: "{{ hostname | split('-') | last }}"
    ipv4_address: "{{ ansible_default_ipv4.address | default(ansible_all_ipv4_addresses | first) }}"
  tasks:
    - name: Update Netbox
      ansible.builtin.include_role:
        name: depin.libs.netbox
