---
- name: Start node
  become: true
  ansible.builtin.systemd_service:
    name: file-server-lin
    daemon_reload: true
    enabled: true
    state: started

# - name: Assert
#   when: "'molecule' in groups"
#   block:
#     - name: Get service facts
#       ansible.builtin.service_facts:
    
#     - name: Check service facts
#       vars:
#         _name: "{{ item }}.service"
#       ansible.builtin.assert:
#         that:
#           - ansible_facts['services'][_name] is defined
#           - ansible_facts['services'][_name]['state'] == 'running'
#           - ansible_facts['services'][_name]['status'] == 'enabled'
#         quiet: true
#       loop: "{{ storagechain_programs }}"
