---
- name: Stop node
  become: true
  ansible.builtin.systemd_service:
    name: file-server-lin
    enabled: false
    state: stopped
  failed_when: false

# - name: Assert
#   when: "'molecule' in groups"
#   block:
#     - name: Get service facts
#       ansible.builtin.service_facts:
    
#     - name: Check service facts
#       vars:
#         _name: "{{ item }}.service"
#       ansible.builtin.assert:
#         that:
#           - ansible_facts['services'][_name]
#           - ansible_facts['services'][_name]['state'] in ['stopped', 'inactive']
#         quiet: true
#       loop: "{{ storagechain_programs }}"
