---
- name: Setup
  hosts: localhost
  gather_facts: true
  become: true
  tasks:
    - name: Install heartbeat
      ansible.builtin.command: sudo hab svc load deeep-network/ilert-heartbeat
      changed_when: false

    - name: Install ESC package
      ansible.builtin.command: sudo hab pkg install deeep-network/esc
      changed_when: false

    - name: Install Grafana Alloy
      when: ansible_virtualization_role == 'guest'
      ansible.builtin.command: sudo hab pkg install deeep-network/grafana-alloy
      changed_when: false

    - name: Set auto-deploy systemd files
      ansible.builtin.template:
        src: "{{ item }}.j2"
        dest: /etc/systemd/system/{{ item }}
        mode: '0644'
      loop:
        - auto-deploy.service
        - auto-deploy.timer

    - name: Enable and start auto-deploy timer
      ansible.builtin.systemd:
        name: auto-deploy.timer
        state: started
        enabled: true
        daemon_reload: true
