---
- name: Setup
  hosts: localhost
  gather_facts: true
  become: true
  tasks:
    - name: Install ESC package
      when: ansible_virtualization_role == 'host'
      ansible.builtin.command: sudo hab pkg install deeep-network/esc
      changed_when: false

    - name: Install Grafana Alloy
      when: ansible_virtualization_role == 'guest'
      ansible.builtin.command: sudo hab pkg install deeep-network/grafana-alloy
      changed_when: false

    - name: Create systemd service files
      ansible.builtin.template:
        src: "{{ item }}.j2"
        dest: /etc/systemd/system/{{ item }}
        mode: '0644'
      loop:
        - hab-supervisor.service
        - auto-deploy.service
        - auto-deploy.timer

    - name: Reload systemctl daemon
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Enable and start services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - hab-supervisor.service
        - auto-deploy.timer

    - name: Install Heartbeat
      ansible.builtin.command: sudo hab svc load deeep-network/ilert-heartbeat
      changed_when: false
