namespace: deeep
name: core
version: 2.0.0
readme: README.md
authors:
- Anthony Anderson anthony@deeep.network

description: "`deeep.core` is just that, the core to our orchestration system powered by Ansible"
license:
- MIT
license_file: LICENSE
tags: []

dependencies:
  ansible.posix: "1.5.4"
  ansible.eda: "2.2.0"
  community.general: "10.2.0"

repository: https://github.com/deeep-network/ansible_collections
documentation: https://docs.deeep.network
homepage: https://deeep.network
issues: https://github.com/deeep-network/ansible_collections/issues

build_ignore: []
