---
- name: Stop service
  become: true
  ansible.builtin.systemd_service:
    name: collector-{{ metrics_parent_role_name }}
    enabled: false
    state: stopped
  failed_when: false

- name: Remove files
  become: true
  ansible.builtin.file:
    path: "{{ _file }}"
    state: absent
  loop:
    - /etc/systemd/system/collector-{{ metrics_parent_role_name }}.service
    - /etc/deeep-network/collectors/{{ metrics_parent_role_name }}.py
  loop_control:
    loop_var: _file
