---
- name: Start {{ service_name }}
  become: true
  ansible.builtin.command:
    cmd: sudo hab svc load deeep-network/{{ service_name }} --group services --strategy rolling --topology leader
    creates: /hab/svc/{{ service_name }}
  changed_when: false
