---
- name: Stop {{ service_name }}
  become: true
  ansible.builtin.command:
    cmd: sudo hab svc unload deeep-network/{{ service_name }}
    removes: /hab/svc/{{ service_name }}
  changed_when: false
