---
- Name: Stopping {{ service_name }}
  ansible.builtin.include_tasks: commands/stop.yml

- name: Uninstall {{ service_name }}
  become: true
  ansible.builtin.command: 
    cmd: hab pkg uninstall deeep-network/{{ service_name }}
  changed_when: false
