- name: Reset node
  become: true
  community.docker.docker_container:
    name: presearch
    image:  presearch/node:{{ presearch_version }}
    restart_policy: unless-stopped
    detach: true
    log_driver: journald
    state: started
    recreate: true
    volumes:
      - presearch-node-storage:/app/node
    env:
      REGISTRATION_CODE: "{{ presearch_code }}"

- name: Assert
  when: "'molecule' in groups"
  block:
    - name: Get container info
      become: true
      community.docker.docker_container_info:
        name: presearch
      register: _presearch

    - name: Check container
      ansible.builtin.assert:
        that:
          - _presearch_pid | int != _presearch['container']['State']['Pid'] | int
          - _presearch['container']['State']['Running']
          - not _presearch['container']['State']['Restarting']
          - not _presearch['container']['State']['OOMKilled']
          - not _presearch['container']['State']['Dead']
        quiet: true
    
    - name: Set pid
      ansible.builtin.set_fact:
        _presearch_pid: "{{ _presearch['container']['State']['Pid'] }}"
