- name: DeEEP Network - Manager
  hosts: localhost
  gather_facts: true
  sources:
    - ansible.eda.webhook:
        host: 127.0.0.1
        port: 33337
  rules:
    - name: Webhook Event
      condition: event.payload is defined
      action:
        run_playbook:
          name: "{{ lookup('ansible.builtin.vars', 'depin.core.' + event.payload.trigger) }}"
