---
- name: Converge
  hosts: molecule
  gather_facts: true
  tasks:
    - name: Get services to test
      delegate_to: localhost
      ansible.builtin.find:
        paths: ../../depin/services/roles
        recurse: false
        file_type: directory
      register: _roles

    - name: Test roles
      vars:
        test_roles: "{{ (fqcn is defined) | ternary([{'path': fqcn}], _roles['files']) }}"
        _fqcn: "depin.services.{{ item['path'] | basename | replace('.yml', '') }}"
        test_role: "{{ ('.yml' in item['path'] or '.' not in item['path']) | ternary(_fqcn, item['path']) }}"
      ansible.builtin.include_tasks:
        file: tests/run.yml
      loop: "{{ test_roles }}"
      loop_control:
        label: "{{ item['path'] | basename }}"
