---
installer_parent_role_name: "{{ ansible_parent_role_names | last | split('.') | last }}"

# installer:
#   version:
#   download:
#   programs:
#     - name: program
#       version: test
#       checksum: somecheck
#     - program_name

installer: # noqa var-naming[no-role-prefix]
  version: "{{ lookup('ansible.builtin.vars', installer_parent_role_name + '_version') }}"
  download: "{{ lookup('ansible.builtin.vars', installer_parent_role_name + '_download_urls') }}"
  programs: "{{ lookup('ansible.builtin.vars', installer_parent_role_name + '_programs') }}"

installer_program_name: "{{ installer_program['name'] | default(installer_program) }}"
installer_program_version: "{{ installer['version'] | default(installer_program['version']) | default('current') }}"
installer_program_dir: /opt/{{ ansible_parent_role_names | last | split('.') | last }}/{{ installer_program_version }}
