---
- name: Presearch {{ presearch_cmd }}
  vars:
    cmd_file: "{{ role_path }}/tasks/commands/{{ presearch_cmd }}.yml"
  when: cmd_file is file
  ansible.builtin.include_tasks:
    file: "{{ cmd_file }}"
