---
- name: Install node
  ansible.builtin.include_role:
    name: depin.core.installer

- name: Copy validation engine
  when: "'guardian-cli-linux' in installed_program['src']"
  become: true
  ansible.builtin.copy:
    src: "{{ installed_program['src'] | dirname }}/validation-engine"
    dest: "{{ installed_program['dest'] | dirname }}"
    remote_src: true
    mode: preserve
  loop: "{{ installed_programs['results'] }}"
  loop_control:
    loop_var: installed_program
    label: linux

- name: Create systemd file
  become: true
  ansible.builtin.template:
    src: templates/systemd.service.j2
    dest: /etc/systemd/system/hychain.service
    mode: '0644'
  
- name: Start node
  ansible.builtin.include_tasks:
    file: commands/start.yml

- name: Install metrics
  ansible.builtin.include_role:
    name: depin.core.metrics
