---
## install dependencies and service


- name: Start
  ansible.builtin.include_tasks: commands/start.yml

- name: Install metrics
  ansible.builtin.include_role:
    name: depin.core.metrics

# @todo - assert correct version installed
# relative to playbook (molecule - default)
- name: Assert Install
  when: "'molecule' in groups"
  block:
    - name: Common install asserts
      ansible.builtin.include_tasks:
        file: tests/install.yml

    # unique asserts go here
