---
- name: Destroy molecule containers
  hosts: molecule
  gather_facts: false
  tasks:
    - name: Stop and remove Orb VM
      delegate_to: localhost
      ansible.builtin.command: orbctl delete {{ inventory_hostname | split('@') | first }}
      changed_when: false
      failed_when: false

- name: Remove dynamic molecule inventory
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Remove dynamic inventory file
      ansible.builtin.file:
        path: ../../inventory/molecule_inventory.yml
        state: absent
