---
- name: Manage LXD containers
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    molecule_inventory:
      molecule:
        hosts: {}
    molecule_yml:
      platforms:
        - name: instance
          image: ubuntu:noble
          user: ansible

  tasks:
    - name: Check if LXD is installed
      ansible.builtin.command: lxd --version
      register: lxd_check
      ignore_errors: true

    - name: Fail if LXD is not installed
      ansible.builtin.fail:
        msg: |
          LXD is not installed on this system.
          Please install LXD before running this playbook.
          For installation instructions, visit: https://linuxcontainers.org/lxd/getting-started-cli/
      when: lxd_check.rc != 0

    - name: Check if LXD is initialized
      ansible.builtin.command: lxd waitready --timeout=5
      register: lxd_initialized
      ignore_errors: true

    - name: Fail if LXD is not initialized
      ansible.builtin.fail:
        msg: "LXD is not initialized or not ready. Please run 'sudo lxd init' manually."
      when: lxd_initialized.rc != 0

    - name: Check if LXD container exists
      command: lxc list "{{ platform['name'] }}" --format=json
      register: lxd_container_info
      ignore_errors: true
      loop: "{{ molecule_yml['platforms'] }}"
      loop_control:
        loop_var: platform

    - name: Debug container existence
      ansible.builtin.debug:
        var: lxd_container_info

    - name: Create LXD containers if not exists
      community.general.lxd_container:
        name: "{{ platform['name'] }}"
        state: started
        source:
          type: image
          mode: pull
          server: https://cloud-images.ubuntu.com/releases
          protocol: simplestreams
          alias: "{{ platform['image'] }}"
      when: lxd_container_info.results[0].stdout == '[]'
      loop: "{{ molecule_yml['platforms'] }}"
      loop_control:
        loop_var: platform

    - name: Add LXD container to molecule_inventory
      vars:
        inventory_partial_yaml: |
          molecule:
            hosts:
              {{ platform['name'] }}:
                ansible_user: {{ platform['user'] }}
      ansible.builtin.set_fact:
        molecule_inventory: >
          {{ molecule_inventory | combine(inventory_partial_yaml | from_yaml, recursive=true) }}
      loop: "{{ molecule_yml['platforms'] }}"
      loop_control:
        loop_var: platform

    - name: Dump molecule_inventory
      ansible.builtin.copy:
        content: |
          {{ molecule_inventory | to_nice_yaml }}
        dest: ../../inventory/molecule_inventory.yml
        mode: '0600'

    - name: Force inventory refresh
      ansible.builtin.meta: refresh_inventory

    - name: Fail if molecule group is missing
      ansible.builtin.assert:
        that: "'molecule' in groups"
        fail_msg: |
          Molecule group was not found inside inventory groups: {{ groups }}
      run_once: true
