---
hychain_cmd: "{{ depin_cmd | default('install') }}"
hychain_programs:
  - guardian-cli-linux

hychain_version: 0.0.1
hychain_download_urls:
  - "https://github.com/HYCHAIN/guardian-node-software/archive/refs/heads/main.zip"

hychain_private_key: "{{ lookup('env', 'HYCHAIN_PRIVATE_KEY') | default(notdefined) | mandatory }}"
