---
push_substrate: "{{ device_substrate | default('lxd') }}"

push_short_hostname: "{{ notdefined | mandatory }}"
push_default_interface: "{{ ansible_default_ipv4.interface }}"

push_vm: "{{ device_vm }}"
push_vm_image: "{{ device_vm_image | default('22.04') }}"
push_vm_default_hostname: vm-{{ push_vm['id'] }}.box.nerd-node.com
push_vm_hostname: "{{ device_vm_hostname | default(push_vm_default_hostname) }}"
push_vm_short_hostname: "{{ push_vm_hostname | split('.') | first }}"

push_vm_ipv4_address: "{{ push_vm['primary_ip']['address'] | default('') | split('/') | first }}"
push_vm_public_ipv4_address: "{{ push_vm_ipv4_address | ansible.utils.ipaddr('public') }}"

push_vm_vcpus: "{{ push_vm['vcpus'] | int }}"
push_vm_memory: "{{ (push_vm['memory'] | int >= 1024) | ternary(push_vm['memory'] | int, '1024') }}MiB"
push_vm_disk: "{{ push_vm['disk'] | int }}GiB"
push_vm_recreate: false
